Fix and update the docker + bats based tests
jenv/jenv pull request #413
Opened 2023-07-26 16:56 UTC by mrmeszaros

In order to make tests green the following needed to be done:
- Fix typo in docker tag: rename to jenv:test
- Remove openjdk 1.6 and its test
- Fix `adding_jdks.bats` tests
- Fix `setting_versions.bats` tests

Additionally I added some improvements:
- Added setup_suite.bash
- Extended adding_jdks with zulu 18 and graalvm
- Refactored `setup` into: `setup_suite`, `setup` and `teardown`
- Added version-name checks to `setting_versions.bats`

Fixes #411

2024-03-16 03:17 UTC, andrewflbarnes requested changes

2024-03-16 03:17 UTC, andrewflbarnes commented on test/Dockerfile
> +RUN curl -L https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.3.3/graalvm-ce-java11-linux-$(arch)-22.3.3.tar.gz | tar xzf - -C /usr/lib/jvm/
If `$(arch)` is `x86_64` should get `amd64`

2024-03-16 03:17 UTC, andrewflbarnes commented on test/adding_jdks.bats
> +  jenv add /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.372.b07-1.el7_9.$_ARCH/jre/
Should probably make this and other add commands not depend on build version as tests are brittle - some of these are out of date again e.g.

```suggestion
@test "add openjdk 1.8.0" {
  jenv add /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.*.el7_9.$_ARCH/jre/
```

2024-03-16 03:17 UTC, andrewflbarnes commented on test/adding_jdks.bats
> +  assert_line --regexp '^ *openjdk64-1.8.0.372$'
As other comment should make these and other assertions not depend on build version as tests are brittle and some of these are out of date again
```suggestion
  assert_line --regexp '^ *1.8.0.[0-9]+$'
  assert_line --regexp '^ *openjdk64-1.8.0.[0-9]+$'
```

2024-05-31 19:30 UTC, mrmeszaros commented
@andrewflbarnes thanks for the review - I think I fixed the issue You mentioned!

2024-07-04 06:58 UTC, mrmeszaros commented on test/Dockerfile
> +RUN curl -L https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.3.3/graalvm-ce-java11-linux-$(arch)-22.3.3.tar.gz | tar xzf - -C /usr/lib/jvm/
Good catch - did that!

2024-07-04 06:59 UTC, mrmeszaros commented on test/adding_jdks.bats
> +  jenv add /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.372.b07-1.el7_9.$_ARCH/jre/
Included a build version finder, to be able to verify the inclusion.

2025-07-16 00:07 UTC, andrewflbarnes approved these changes

2025-07-16 00:07 UTC, merged